"""Add failed_log to Job

Revision ID: 6339d9e9fc7c
Revises: 8c124eb7fc8b
Create Date: 2023-10-16 15:59:51.859280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6339d9e9fc7c'
down_revision: Union[str, None] = '8c124eb7fc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('failed_log', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'failed_log')
    # ### end Alembic commands ###
